INSERT INTO MALTE(nome, ebc, quantidade) VALUES('pilsen',5.0,200.0);
INSERT INTO MALTE(nome, ebc, quantidade) VALUES('pale ale',10,150);
INSERT INTO MALTE(nome, ebc, quantidade) VALUES('crystal',200,25);
INSERT INTO MALTE(nome, ebc, quantidade) VALUES('black',250,25);



INSERT INTO LUPULO(nome, alfaacido, quantidade) VALUES('magnum',12.9,5000);
INSERT INTO LUPULO(nome, alfaacido, quantidade) VALUES('Amarillo',8,10000);
INSERT INTO LUPULO(nome, alfaacido, quantidade) VALUES('Cascade ',5,2000);
INSERT INTO LUPULO(nome, alfaacido, quantidade) VALUES('Galaxy',11,2500);



INSERT INTO FERMENTO(nome, quantidade) VALUES('US-05',10);
INSERT INTO FERMENTO(nome, quantidade) VALUES('WB-06',8);
INSERT INTO FERMENTO(nome, quantidade) VALUES('W-32/70',5);



INSERT INTO RECEITA(estilo,fg_esperada, nome , og_esperada, fermento_id) VALUES('lager', 1010, 'pilsen', 1044, 1);
INSERT INTO RECEITA(estilo,fg_esperada, nome, og_esperada, fermento_id) VALUES('lager', 1010, 'german', 1044, 1);
INSERT INTO RECEITA(estilo,fg_esperada, nome, og_esperada, fermento_id) VALUES('ale', 1010, 'ipa', 1056, 1);
INSERT INTO RECEITA(estilo,fg_esperada, nome, og_esperada, fermento_id) VALUES('ale', 1010, 'apa', 1050, 2);



INSERT INTO RECEITA_LUPULO(QUANTIDADE,LUPULO_ID,RECEITA_ID) VALUES(100,1,1);
INSERT INTO RECEITA_LUPULO(QUANTIDADE,LUPULO_ID,RECEITA_ID) VALUES(250,2,1);
INSERT INTO RECEITA_LUPULO(QUANTIDADE,LUPULO_ID,RECEITA_ID) VALUES(325,3,1);
INSERT INTO RECEITA_LUPULO(QUANTIDADE,LUPULO_ID,RECEITA_ID) VALUES(10,4,1);



INSERT INTO RECEITA_MALTE(QUANTIDADE,MALTE_ID,RECEITA_ID) VALUES(25,1,1);
INSERT INTO RECEITA_MALTE(QUANTIDADE,MALTE_ID,RECEITA_ID) VALUES(8,2,1);
INSERT INTO RECEITA_MALTE(QUANTIDADE,MALTE_ID,RECEITA_ID) VALUES(100,3,1);
INSERT INTO RECEITA_MALTE(QUANTIDADE,MALTE_ID,RECEITA_ID) VALUES(12,4,1);

